name: Bug Report
description: File a bug report to help us improve ROSTRY
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste or drag images here...

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Google Pixel
        - Samsung Galaxy
        - OnePlus
        - Xiaomi
        - Realme
        - Other Android Device
    validations:
      required: true

  - type: dropdown
    id: android-version
    attributes:
      label: Android Version
      description: What version of Android are you running?
      options:
        - Android 14
        - Android 13
        - Android 12
        - Android 11
        - Android 10
        - Android 9 or below
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of ROSTRY are you using? (Check in Settings > About)
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: user-role
    attributes:
      label: User Role
      description: Which role are you using in the app?
      options:
        - General User
        - Farmer
        - Enthusiast
        - Admin

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Trace
      description: If applicable, provide crash logs or error messages.
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any other relevant information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required information above
          required: true
        - label: I am using the latest version of the app (or have noted my version)
          required: true
