name: Feature Request
description: Suggest a new feature or enhancement for ROSTRY
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us evaluate your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What user need does it address?
      placeholder: This feature would solve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Describe the user experience and functionality.
      placeholder: The feature should work like this...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: I also considered...

  - type: checkboxes
    id: user-types
    attributes:
      label: User Type
      description: Which user types would benefit from this feature?
      options:
        - label: General User
        - label: Farmer
        - label: Enthusiast
        - label: Admin
        - label: All Users

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Significantly impacts usability
        - Critical - Blocking major workflow
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the app does this feature relate to?
      options:
        - Authentication
        - Profile Management
        - Social Features
        - Marketplace
        - Farm Monitoring
        - Analytics
        - Transfer System
        - Notifications
        - Settings
        - Other

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Designs
      description: If you have any mockups, wireframes, or design ideas, attach them here.
      placeholder: Paste or drag images here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or screenshots about the feature request.
      placeholder: Any other relevant information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested before
          required: true
        - label: I have provided detailed information about the feature
          required: true
        - label: This feature aligns with the goals of ROSTRY
          required: true
