package com.rio.rostry.utils.export

import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Path
import android.graphics.Typeface
import com.rio.rostry.domain.pedigree.PedigreeBird
import com.rio.rostry.domain.pedigree.PedigreeTree
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Shared logic for drawing a Pedigree Certificate on a Canvas.
 * Used by both PDF and Image generators.
 */
class PedigreeRenderer(
    private val canvas: Canvas,
    private val width: Int,
    private val height: Int
) {
    private val margin = 40f

    fun draw(tree: PedigreeTree) {
        val paint = Paint().apply { isAntiAlias = true }

        // Background
        paint.color = Color.WHITE
        canvas.drawRect(0f, 0f, width.toFloat(), height.toFloat(), paint)

        // Ornamental Border
        paint.color = Color.parseColor("#1B5E20") // Brand Green
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 4f
        canvas.drawRect(20f, 20f, width - 20f, height - 20f, paint)
        paint.strokeWidth = 1f
        canvas.drawRect(26f, 26f, width - 26f, height - 26f, paint)

        // Title
        paint.style = Paint.Style.FILL
        paint.textSize = (width / 20f).coerceAtLeast(24f) // Responsive text size
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        paint.textAlign = Paint.Align.CENTER
        paint.color = Color.parseColor("#1B5E20")
        canvas.drawText("CERTIFICATE OF PEDIGREE", width / 2f, 80f, paint)

        // Subtitle
        paint.textSize = 14f
        paint.typeface = Typeface.SANS_SERIF
        paint.color = Color.BLACK
        canvas.drawText("Generated by ROSTRY App", width / 2f, 105f, paint)

        // Main Bird Info
        drawMainBirdInfo(tree.bird)

        // Tree
        drawGeneticsTree(tree)

        // Footer
        paint.textAlign = Paint.Align.LEFT
        paint.textSize = 10f
        paint.color = Color.GRAY
        val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale.getDefault())
        canvas.drawText("Date: ${dateFormat.format(Date())}", margin, height - 30f, paint)
        
        paint.textAlign = Paint.Align.RIGHT
        canvas.drawText("ROSTRY - Poultry Management", width - margin, height - 30f, paint)
    }

    private fun drawMainBirdInfo(bird: PedigreeBird) {
        val paint = Paint().apply { isAntiAlias = true }
        val cx = width * 0.2f // Left side
        val cy = height * 0.5f // Center vertically

        // Draw Circle placeholder for image
        paint.style = Paint.Style.STROKE
        paint.color = Color.LTGRAY
        paint.strokeWidth = 2f
        val radius = 50f
        canvas.drawCircle(cx, cy - 30, radius, paint)
        
        // Initials or Icon placeholder
        paint.style = Paint.Style.FILL
        paint.textAlign = Paint.Align.CENTER
        paint.textSize = 30f
        paint.color = Color.LTGRAY
        val initial = bird.name.firstOrNull()?.toString() ?: "?"
        canvas.drawText(initial, cx, cy - 20, paint)
        
        // Name
        paint.textSize = 20f
        paint.typeface = Typeface.create(Typeface.SERIF, Typeface.BOLD)
        paint.color = Color.BLACK
        canvas.drawText(bird.name, cx, cy + 40, paint)

        // Breed
        paint.textSize = 14f
        paint.typeface = Typeface.SANS_SERIF
        paint.color = Color.DKGRAY
        canvas.drawText(bird.breed ?: "Unknown Breed", cx, cy + 60, paint)
        
        // Gender
        val genderColor = if (bird.name.firstOrNull()?.uppercaseChar() in 'A'..'M') Color.BLUE else Color.MAGENTA
        paint.color = genderColor
        canvas.drawText(if (genderColor == Color.BLUE) "Male" else "Female", cx, cy + 80, paint)
    }

    private fun drawGeneticsTree(tree: PedigreeTree) {
        val startX = width * 0.4f
        val startY = height * 0.5f
        
        // Layout Config
        val levelWidth = width * 0.25f
        val verticalSpacing = height * 0.2f
        
        // Lines to Parents (Level 1)
        val sireY = startY - verticalSpacing
        val damY = startY + verticalSpacing
        val parentX = startX
        
        val rootX = width * 0.2f + 50f // Edge of main bird circle circle roughly
        
        // Draw lines from root to parents
        // Actually, let's draw lines from the right side of main bird area
        val connectX = width * 0.28f
        
        drawLine(connectX, startY, parentX, sireY)
        drawLine(connectX, startY, parentX, damY)

        // Draw Parents
        drawNode(tree.sire, parentX, sireY, "Sire")
        drawNode(tree.dam, parentX, damY, "Dam")

        // Level 2: Grandparents
        val gpX = parentX + levelWidth
        val gpDiff = verticalSpacing * 0.5f
        
        // Sire's parents
        if (tree.sire != null) {
            drawLine(parentX + 70, sireY, gpX, sireY - gpDiff)
            drawLine(parentX + 70, sireY, gpX, sireY + gpDiff)
            
            drawNode(tree.sire.sire, gpX, sireY - gpDiff, "Paternal G.Sire")
            drawNode(tree.sire.dam, gpX, sireY + gpDiff, "Paternal G.Dam")
        }

        // Dam's parents
        if (tree.dam != null) {
            drawLine(parentX + 70, damY, gpX, damY - gpDiff)
            drawLine(parentX + 70, damY, gpX, damY + gpDiff)
            
            drawNode(tree.dam.sire, gpX, damY - gpDiff, "Maternal G.Sire")
            drawNode(tree.dam.dam, gpX, damY + gpDiff, "Maternal G.Dam")
        }
    }

    private fun drawNode(node: PedigreeTree?, x: Float, y: Float, relationship: String) {
        val paint = Paint().apply { isAntiAlias = true }
        
        val boxW = 120f
        val boxH = 40f
        val left = x
        val top = y - boxH / 2
        
        // Box background
        paint.color = Color.parseColor("#F5F5F5")
        paint.style = Paint.Style.FILL
        canvas.drawRoundRect(left, top, left + boxW, top + boxH, 8f, 8f, paint)
        
        // Box border
        paint.color = Color.LTGRAY
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = 1f
        canvas.drawRoundRect(left, top, left + boxW, top + boxH, 8f, 8f, paint)

        if (node != null) {
            paint.style = Paint.Style.FILL
            paint.textAlign = Paint.Align.LEFT
            
            // Name
            paint.textSize = 10f
            paint.typeface = Typeface.create(Typeface.SANS_SERIF, Typeface.BOLD)
            paint.color = Color.BLACK
            // Truncate name if too long
            val name = if (node.bird.name.length > 15) node.bird.name.take(13) + "..." else node.bird.name
            canvas.drawText(name, left + 8, top + 15, paint)

            // Breed
            paint.textSize = 8f
            paint.typeface = Typeface.SANS_SERIF
            paint.color = Color.DKGRAY
            val breed = node.bird.breed ?: "Unknown"
             val breedText = if (breed.length > 18) breed.take(16) + "..." else breed
            canvas.drawText(breedText, left + 8, top + 30, paint)
        } else {
            paint.style = Paint.Style.FILL
            paint.textAlign = Paint.Align.CENTER
            paint.textSize = 10f
            paint.color = Color.LTGRAY
            canvas.drawText("Unknown", left + boxW/2, top + 25, paint)
        }

        // Relationship Label
        paint.textAlign = Paint.Align.LEFT
        paint.textSize = 8f
        paint.color = Color.parseColor("#1B5E20") // Green
        paint.style = Paint.Style.FILL
        canvas.drawText(relationship, left, top - 4, paint)
    }

    private fun drawLine(x1: Float, y1: Float, x2: Float, y2: Float) {
        val paint = Paint().apply {
            color = Color.GRAY
            strokeWidth = 1f
            style = Paint.Style.STROKE
        }
        val path = Path()
        path.moveTo(x1, y1)
        val midX = (x1 + x2) / 2
        path.cubicTo(midX, y1, midX, y2, x2, y2)
        canvas.drawPath(path, paint)
    }
}
